name: CI with Caching

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-with-cache:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Create virtual environment
        run: uv venv

      - name: Cache uv dependencies
        id: cache-uv
        uses: actions/cache@v4
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: cache-175db45

      - name: Install dependencies
        run: uv pip install -r requirements.txt

      - name: prime-cache-175db45
        run: |
          echo "cache-hit=${{ steps.cache-uv.outputs.cache-hit }}"
          if [[ "${{ steps.cache-uv.outputs.cache-hit }}" == "true" ]]; then
            echo "Cache hit! Dependencies were restored."
          else
            echo "Cache miss. Dependencies were installed and cache will be saved."
          fi
          
# trigger cache tets